# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      # - name: Create a env file
      #   run: cp .env.testingexample .env

      - name: Creating a env file
        run: |
          touch .env  
          echo HOST=127.0.0.1 >> .env
          echo PORT=3333 >> .env
          echo NODE_ENV=development >> .env
          echo APP_NAME=AdonisJs >> .env
          echo APP_URL=http://127.0.0.1:3333 >> .env
          echo CACHE_VIEWS=false >> .env
          echo APP_KEY=K33uHzb1THpekPIBsPgRxGpbLb6HETHr >> .env
          echo DB_CONNECTION=sqlite >> .env
          echo DB_HOST=127.0.0.1 >> .env
          echo DB_PORT=3306 >> .env
          echo DB_USER=root >> .env
          echo DB_PASSWORD= >> .env
          echo DB_DATABASE=adonis >> .env
          echo HASH_DRIVER=bcrypt >> .env
          cat .env

      - run: npm ci
      - name: Testing
        run: npm test
      
